# Generated by Django 2.1.3 on 2018-11-27 15:02

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_propuesta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carrera', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Departamento', chained_model_field='id_departamento_id', on_delete=django.db.models.deletion.CASCADE, to='agenda.Carreras')),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('propuesta_codigo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Carreras')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Departamentos'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='Materia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Carrera', chained_model_field='propuesta_codigo_id', on_delete=django.db.models.deletion.CASCADE, to='agenda.Materias'),
        ),
        migrations.AddField(
            model_name='carreras',
            name='id_departamento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Departamentos'),
        ),
    ]
