# Generated by Django 2.1 on 2018-09-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='Agenda',
        ),
    ]
