# Generated by Django 2.1.2 on 2018-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasUsuarios', '0002_auto_20181029_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='userAdmin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
